### ISSUE TITLE
tsconfig.json - react necessary?

### ISSUE THREAD

**Issue by hansschenker** [blaumeise20/template-jsx#7]
{
    "extends": "../tsconfig.base.json",
    "compilerOptions": {
        "outDir": "../dist/test",
        "jsx": "react", // why is react here, should run without react, is it because Typescript needs it?
        "jsxFactory": "jsxt.createElement",
        "jsxFragmentFactory": "jsxt.Fragment",
        "noImplicitAny": true,
        "declaration": false
    },
    "include": ["."]
}

**Comment by blaumeise20** [comment]
Yes, this is needed. `react` doesn't specify the library React in this case, but the JSX transformation rules used by React. You can look into https://www.typescriptlang.org/tsconfig#jsx for more information. Note that `React.createElement` is replaced by the custom function in `jsxFactory`.
